id = "psyco"
name = "Psyco"
version = "0.1.0"
schema_version = 1
authors = ["Mewax07"]
description = "Language support for Psyco"

[grammars.psyco]
repository = "https://github.com/Mewax07/psyco-tree-sitter"
commit = "470ef4cab3279cc061980a7aa12d44182233eaff"

[language_servers.psyco-lsp]
name = "Psyco LSP"
languages = ["Psyco"]
